:doctype: book
:toc: left
:toclevels: 2
:source-highlighter: highlightjs

[[Post-API]]
== Post API

[[Get-Post-Page]]
=== 게시글 조회
operation::post-controller-test/get-post-page[snippets="http-request,query-parameters,response-fields"]

[[Get-Post-By-Pid]]
=== 게시글 조회 ( PK )
operation::post-controller-test/get-post[snippets="http-request,path-parameters,response-fields"]

[[Get-Post-By-Uid]]
=== 게시글 조회 ( UID )
operation::post-controller-test/get-post-by-uid[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Post-By-Title]]
=== 게시글 조회 ( 제목 )
operation::post-controller-test/get-post-by-title[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Post-By-Username]]
=== 게시글 조회 ( 유저명 )
operation::post-controller-test/get-post-by-username[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Post-By-Category]]
=== 게시글 조회 ( 카테고리 )
operation::post-controller-test/get-post-by-category[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Post-Like]]
=== 게시글 좋아요 조회
operation::post-controller-test/get-post-like[snippets="http-request,path-parameters,response-fields"]

[[Get-Post-Like-True-Count]]
=== 게시글 좋아요 (true) 카운트
operation::post-controller-test/get-post-like-true-count[snippets="http-request,path-parameters,http-response"]

[[Post-Post]]
=== 게시글 저장
operation::post-controller-test/save-post[snippets="http-request,request-fields,http-response"]

[[Put-Post-Like]]
=== 게시글 좋아요 or 싫어요 저장
operation::post-controller-test/save-post-like[snippets="http-request,request-fields,http-response"]

[[Delete-Post]]
=== 게시글 삭제
operation::post-controller-test/delete-post[snippets="http-request,path-parameters,http-response"]

[[Delete-Post-Like]]
=== 게시글 좋아요 삭제
operation::post-controller-test/delete-post-like[snippets="http-request,path-parameters,http-response"]