[[Comment-API]]
== Comment API

[[Get-Comment-By-Post]]
=== 댓글 조회 ( 게시글 )
operation::comment-controller-test/get-comments-by-post[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Comment-By-User]]
=== 댓글 조회 ( 유저 )
operation::comment-controller-test/get-comments-by-user[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Comment-Like-By-User]]
=== 댓글 좋아요 조회 ( 유저 )
operation::comment-controller-test/get-comment-like-by-user[snippets="http-request,path-parameters,response-fields"]

[[Get-Comment-Like-By-Comment]]
=== 댓글 좋아요 조회 ( 댓글 )
operation::comment-controller-test/get-comment-like-by-comment[snippets="http-request,path-parameters,response-fields"]

[[Get-Count-Comment-Like]]
=== 댓글 좋아요 개수 조회
operation::comment-controller-test/get-count-comment-like[snippets="http-request,path-parameters,http-response"]

[[Save-Comment]]
=== 댓글 저장
operation::comment-controller-test/save-comment[snippets="http-request,request-fields,http-response"]

[[Update-Comment]]
=== 댓글 수정
operation::comment-controller-test/update-comment[snippets="http-request,request-fields,http-response"]

[[Put-Comment]]
=== 댓글 저장 or 수정
operation::comment-controller-test/put-comment-like[snippets="http-request,request-fields,http-response"]

[[Delete-Comment]]
=== 댓글 삭제
operation::comment-controller-test/delete-comment[snippets="http-request,path-parameters,http-response"]

[[Delete-Comment-Like]]
=== 댓글 좋아요 삭제
operation::comment-controller-test/delete-comment-like[snippets="http-request,path-parameters,http-response"]