= REST Docs
:snippets: ../../../build/generated-snippets
spring-boot 3.1.2
:doctype: book
:toc: left
:toclevels: 2
:source-highlighter: highlightjs

include::Test-API.adoc[]

[[Post-API]]
== Post API

[[Get-Post-Page]]
=== 게시글 조회
operation::post-controller-test/get-post-page[snippets="http-request,query-parameters,http-response,response-fields"]

[[Save-Post]]
=== 게시글 저장
operation::post-controller-test/save-post[snippets="http-request,request-fields,http-response,response-fields"]

[[Get-Post-Title]]
=== 게시글 조회 ( 제목 )
operation::post-controller-test/get-post-title[snippets="http-request,path-parameters,query-parameters,http-response,response-fields"]

[[Get-Post-Username]]
=== 게시글 조회 ( 유저명 )
operation::post-controller-test/get-post-username[snippets="http-request,path-parameters,query-parameters,http-response,response-fields"]

[[Get-Post-Like]]
== 게시글 좋아요 조회
operation::post-controller-test/get-post-like[snippets="http-request,path-parameters,http-response,response-fields"]

[[Save-Post-Like]]
== 게시글 좋아요 싫어요 추가
operation::post-controller-test/save-post-like[snippets="http-request,request-fields,http-response,response-fields"]

[[Delete-Post-Like]]
== 게시글 삭제
operation::post-controller-test/delete-like[snippets="http-request,path-parameters,http-response,response-body"]