[[Post-API]]
== Post API

[[Get-Post-Page]]
=== 게시글 조회
operation::post-controller-test/get-post-page[snippets="http-request,query-parameters,response-fields"]

[[Get-Post-By-Pid]]
=== 게시글 조회 ( PK )
operation::post-controller-test/get-post[snippets="http-request,path-parameters,response-fields"]

[[Get-Post-By-Title]]
=== 게시글 조회 ( 제목 )
operation::post-controller-test/get-post-by-title[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Post-By-Username]]
=== 게시글 조회 ( 유저명 )
operation::post-controller-test/get-post-by-username[snippets="http-request,path-parameters,query-parameters,response-fields"]

[[Get-Post-Like]]
=== 게시글 좋아요 조회
operation::post-controller-test/get-post-like[snippets="http-request,path-parameters,response-fields"]

[[Post-Post]]
=== 게시글 저장
operation::post-controller-test/save-post[snippets="http-request,request-fields,http-response,response-fields"]

[[Put-Post-Like]]
=== 게시글 좋아요 or 싫어요 저장
operation::post-controller-test/save-post-like[snippets="http-request,request-fields,http-response,response-fields"]

[[Delete-Post]]
=== 게시글 삭제
operation::post-controller-test/delete-post[snippets="http-request,path-parameters,http-response"]

[[Delete-Post-Like]]
=== 게시글 좋아요 삭제
operation::post-controller-test/delete-post-like[snippets="http-request,path-parameters,http-response"]